### ISSUE TITLE
 dist files for directly using in HTML document

### ISSUE THREAD

**Issue by AgentSmith0** [watergis/mapbox-gl-legend#11]
Please publish compiled dist files for using them as script tag in HTML.

**Comment by JinIgarashi** [comment]
@AgentSmith0 It would be great if we can publish the library for script tag. However, I am not very sure how to do this. Do you know it? I also welcome a PR from anybody for this issue.

**Comment by JinIgarashi** [comment]
@AgentSmith0 Now you can directly use scripts through CDN since [v1.2.0](https://github.com/watergis/mapbox-gl-legend/releases/tag/v1.2.0).

**Comment by AgentSmith0** [comment]
@JinIgarashi Sorry for the late response. Thank you very much! It works fine.
