### ISSUE TITLE
Cross-Browser Compatibility

### ISSUE THREAD

**Issue by SamiAlavi** [watergis/mapbox-gl-legend#13]
Does this library work the same way on all browsers? I am currently using: 
- `angular v11.2.10`
- `typescript v4.1.5`
- `mapbox-gl v1.13.1`
- `mapbox-gl-legend v1.1.5`

The legend works great on `Chrome v93.0.4577.63` and `Edge v92.0.902.84` but is acting weird on `Firefox v91.0.2`. I have attached the screenshots below. From what I have observed on Firefox
- When it is first loaded, the size of the SVG circles keep on increasing
- On closing and then opening the legend, the SVG circles go back to the original size
- Continuously checking and unchecking the 'Only rendered' checkbox, the size of the SVG circles keep on increasing

---

Chrome: 
![image](https://user-images.githubusercontent.com/32700289/131837639-90ee9b95-0cad-4fd6-8402-3c1a328a2343.png)

Firefox: 
![image](https://user-images.githubusercontent.com/32700289/131837464-42f86e1b-819c-4a77-99bc-ad89cbd9b0d7.png)

**Comment by JinIgarashi** [comment]
@SamiAlavi thank you for reporting the bug. In fact I have never tested it in Firefox…I am not sure what causes this problem…
