### ISSUE TITLE
Using import with the 1.2.0 library causes a build error

### ISSUE THREAD

**Issue by fwextensions** [watergis/mapbox-gl-legend#18]
**Describe the bug**
If the library is imported with `import`, upgrading from 1.1.7 to 1.2.0 causes an error at build time, about not being able to find `mapboxgl`.

**To Reproduce**
1. Go to the demo sandbox
2. Change the `mapbox-gl-legend` version in package.json to 1.2.0

As soon as it starts to rebuild, there's an error, shown below. 

**Expected behavior**
No error!

**Screenshots**

![image](https://user-images.githubusercontent.com/61631/142559166-0a383c8e-d6ed-48bc-884a-94e2f22f247a.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 95

**Additional context**
Caused by changes for CDN support?

**Comment by JinIgarashi** [comment]
@fwextensions Thank you for raising the issue! I have fixed it now. Please use v1.2.1.

**Comment by fwextensions** [comment]
Thanks for the quick fix!  v1.2.1 doesn't show that error now.
