### ISSUE TITLE
Minor incompatibilities with maplibre-gl-js

### ISSUE THREAD

**Issue by geraldo** [watergis/mapbox-gl-legend#24]
Thanks for your plugin, it works great! Lately I migrated some sites from mapbox-gl to maplibre-gl and your plugin mostly works well. I only have two issues:

1. Layer legends only show up after checking "Only rendered" checkbox, both with activated and deactivated parameter `onlyRendered`.
2. 404 not found error show up in console trying to load `undefined.json` and `undefined@2x.png`. Are these files necessary for the plugin to work correctly?

This happens both on Chrome and Firefox using latest maplibre 2.4.0.

**Comment by JinIgarashi** [comment]
@geraldo please use maplibre version’s plugin

https://github.com/watergis/maplibre-gl-legend
