### ISSUE TITLE
Configure the title of the legend

### ISSUE THREAD

**Issue by JacobGeoGeek** [watergis/mapbox-gl-legend#27]
**Is your feature request related to a problem? Please describe.**
After looking at the Options values, no options exist to override the Title of the Legend.

**Describe the solution you'd like**
It will interest the user to Change the Title to something else. If the user does not specify a Title, legend control must use the **Legend** as a default title.

**Comment by JinIgarashi** [comment]
@JacobGeoGeek I am sorry for responding late. Thanks for the PR. I have merged and released it as v1.2.6. Is it possible to create the same PR for [maplibre-gl-legend](https://github.com/watergis/maplibre-gl-legend)? It would be nice this title option in maplibre, too.

**Comment by JinIgarashi** [comment]
Sorry maplibre one already has it via this PR.

https://github.com/watergis/maplibre-gl-legend/pull/1

it is very difficult for me to manage almost same code in two repo. I need to merge mapboxoneto maplibre repo…

**Comment by JacobGeoGeek** [comment]
@JinIgarashi No worries, at least some have thought of this idea for MapLibre.
